#ifndef ASSETSANIMSPEED_H
#define ASSETSANIMSPEED_H

#define PLAY_FULL_ANIM 2
#define MOMENTAL_SPEED_ANIM 1

//PLAYER
//TIME
//SPEED
#define PLAYER_WALK_SPEED_ANIM 5
#define PLAYER_MINE_SPEED_ANIM 4
#define PLAYER_ATTACK_SPEED_ANIM 5


//ENEMY
//TIME
#define ENEMY_CORPSE_FALLING_TIME_ANIM 20
#define ENEMY_RECEIVING_DAMAGE_TIME_ANIM 120

//SPEED
#define ENEMY_WALK_SPEED_ANIM 5
#define ENEMY_ATTACK_SPEED_ANIM 5
#define ENEMY_FALL_DIE_SPEED_ANIM 6





#endif